### ISSUE TITLE
Is there documentation on response byte layout

### ISSUE THREAD

**Issue by probtask** [aerospike/aerospike-client-java#165]
I am poking around with the java client a bit, but find it a bit hard to understand how to parse the response without a doc. Is there response memory layout lying somewhere?

For example figuring out how to read the `dataBuffer` can be a bit of a pain if I don't already know the layout.

**Comment by BrianNichols** [comment]
We used to document our wire protocol and some customers even wrote custom clients using those documents, but we now highly discourage using custom clients.

The reason is product features are constantly being added/refined and it's too difficult to guarantee compatibility for all versions of the wire protocol specification.

**Comment by probtask** [comment]
Ah I see, thanks
