### ISSUE TITLE
4.4.19 client pom on Maven Central refers to "missing" `aerospike-parent`

### ISSUE THREAD

**Issue by mcculls** [aerospike/aerospike-client-java#204]
Compare https://repo1.maven.org/maven2/com/aerospike/aerospike-client/4.4.19/aerospike-client-4.4.19.pom with https://repo1.maven.org/maven2/com/aerospike/aerospike-client/4.4.18/aerospike-client-4.4.18.pom

Previous releases have deployed a smaller pom to Maven Central that uses `oss-parent` as the parent and omits various build-related sections. The recent 4.4.19 release has deployed the original build pom which uses `aerospike-parent` as its parent. AFAICT the `aerospike-parent` pom has never been deployed to Maven Central.

While this shouldn't affect everyday use of the client, it could affect Maven tools that attempt to parse the deployed client pom and can't find the missing parent.

**Comment by BrianNichols** [comment]
I attempted to re-upload aerospike-client-4.4.19 with the smaller pom seen in previous versions. The change has not been reflected in maven central yet.

If this continues to cause problems, you can use [aerospike-client-bc-4.4.19](https://search.maven.org/artifact/com.aerospike/aerospike-client-bc/4.4.19/jar) which already contains the smaller pom. This alternate library has the same functionality, but uses BouncyCastle crypto instead of GNU crypto.

**Comment by mcculls** [comment]
thanks - you may need to contact https://issues.sonatype.org/projects/OSSRH to get the updated pom to maven central (by default it doesn't allow updating of already published artifacts)

**Comment by BrianNichols** [comment]
I had to bump the client version to 4.4.20 in order to publish the correct pom file.
