### ISSUE TITLE
Problem reading Date type with client version 7.X

### ISSUE THREAD

**Issue by mikrobestie** [aerospike/aerospike-client-java#308]
Hello, we need to upgrade our java project to newer version of the aerospike client (we are using it via the com.aerospike:spring-data-aerospike library).
Out record structure (bins) used to be like this:
```
String key -> HashMap
    String key -> HashMap
        String key -> Date
```
This was working with aerospike java client version up to 6. However, the same records, after upgrade to client version 7+, are being read like this:
```
String key -> HashMap
    String key -> HashMap
        String key -> byte array
```
and Spring is not being able to convert byte array to Date object, so it fails to read the structure properly.

Is it something we need to configure, or is it a bug?
Thank you

**Comment by BrianNichols** [comment]
The java client removed support for java binary serialization in version 7.0.0 due to it being a security risk (CVE-2023-36480).

https://download.aerospike.com/download/client/java/notes.html#7.0.0
https://aerospike.com/developer/client/incompatible?client=java#version-700

Since date is not an Aerospike datatype, it used to be serialized using java binary serialization. The byte[] you are now seeing is the java serialized date in it's raw form. You can convert the byte[] to a date using the following with client version 7.1.0:

```java
try (ByteArrayInputStream bis = new ByteArrayInputStream(bytes, 0, bytes.length)) {
    try (ObjectInputStream ois = new ObjectInputStream(bis)) {
        return ois.readObject();
    }
}
```

After conversion, I recommend changing the date map key to a 64 bit integer:

```
long dt = date.getTime();
```

This may also require using a newer version of the com.aerospike:spring-data-aerospike library.

**Comment by mikrobestie** [comment]
Thank you for answering, will try to migrate just to supported types. Closing
