### ISSUE TITLE
it seems java api query result lost userKey

### ISSUE THREAD

**Issue by jiucai** [aerospike/aerospike-client-java#44]
my test code:

> Key key = null;
>        RecordSet rs = client.query(null, stmt);
>
>        try {
>            while (rs.next()) {
>                key = rs.getKey();
>                Record record = rs.getRecord();

>               System.out.println(">>>query out key: " + key + " record: " + record);
>            }
>       } finally {
>            rs.close();
>        }

and the original Key class:

>  @Override
> 	public String toString() {
> 		return this.namespace + ":" + this.setName + ":" + this.userKey + ":" + >  Buffer.bytesToHexString(this.digest);
> 	}

test result:
saved key: test:mdid_set:test001:8bfddc9ba6cbdf70e45d4f7bd3c0b483b940de03, 
query result:
key2:test:mdid_set:null:8bfddc9ba6cbdf70e45d4f7bd3c0b483b940de03

### And there is no method to get userKey.

Is this a bug or it designs like this.
I used server : aerospike-server-community-3.5.15

**Comment by BrianNichols** [comment]
This happens by design.  See API reference:  http://www.aerospike.com/apidocs/java/com/aerospike/client/Key.html

*Initialize key from namespace, optional set name and user key. The set name and user defined key are converted to a digest before sending to the server. The user key is not used or returned by the server by default. If the user key needs to persist on the server, use one of the following methods:*

* Set "WritePolicy.sendKey" to true. In this case, the key will be sent to the server for storage on writes and retrieved on multi-record scans and queries.
* Explicitly store and retrieve the key in a bin.

**Comment by jiucai** [comment]
@BrianNichols

Thanks, I will use both methods.
