### ISSUE TITLE
isConnected() always return true even if there is no available nodes

### ISSUE THREAD

**Issue by PostalBear** [aerospike/aerospike-client-java#52]
Hi, 

During my local investigation I found that isConnected() always return true, if there is no nodes available. 

My setup is done in a way that I have just one Aerospike instance.
After startup of my application I manually shutdown Aerospike instance and I expect that this method will return false (since there is no instance to connect to).
Instead it always returns true. 
 
As I can see from sources this method could return false only in two cases:
* if client has been closed (tendValid is false)
* if there is no nodes

Problem is that Tend thread never deletes last node even if it is unavailable.
from __com.aerospike.client.cluster.Cluster__:
```java
			switch (nodes.length) {
			case 1:
				// Single node clusters rely on whether it responded to info requests.
				if (node.failures >= 5) {
					// 5 consecutive info requests failed. Try seeds.
					if (seedNodes(false)) { // <--- Is negation missed here ? it always return false in my case
						removeList.add(node);
					}
				}
				break;
				
```
seedNodes(false) return false in my case and It prevents thread from removing this last node.
And this is the root of this problem.  

Is it correct behavior or I understood semantics of this method incorrectly ?

**Comment by BrianNichols** [comment]
The tend thread used to drop nodes based on the number of consecutive transaction failures.  Unfortunately, This methodology didn't work well with clusters under heavy load, because a large number of timeout caused nodes to be dropped even when the server cluster maps said they were in the cluster and cluster data partitions were not migrated.

The code was changed to only drop nodes when the server cluster maps says they should be dropped.  The single node cluster is a special case because there is no other node that references the suspect node.  Therefore, the seed nodes are attempted.  If a seed was found, it is used instead of the final node (remove node).  If a seed was not found, then continuing to try the final node is better than nothing.

IsConnected() needs to be independent on whether nodes are dropped or not.  We will change IsConnected() to return false when all nodes haven't responded to cluster tend requests for 5 consecutive iterations (usually 5 seconds).

**Comment by BrianNichols** [comment]
Java client has been released.
