### ISSUE TITLE
Support for Aerospike client to seamlessly migrate without downtime when Server enables security

### ISSUE THREAD

**Issue by ashwinjagadeesh** [aerospike/aerospike-client-java#70]
Currently, it is expected to do a restart the client with user and password field set in ClientPolicy when Server enables security. This creates a downtime in the client's end. Please provide an implementation where client(provided with future security credentials to connect to server), automatically switches to use the credentials, when the server enables security.

**Comment by BrianNichols** [comment]
I'm not sure how this would work.  If security credentials change, the previously authenticated sockets sitting in the connection pools would have to be closed.  Otherwise, you would be issuing future commands on mix of old and new security credentials.

Closing all connection pool sockets is essentially restarting the client.

**Comment by ashwinjagadeesh** [comment]
Changing of the security credentials is fine, as we can have two sets of credentials, move all clients to the new creds and disable the old one. Thereby i can ensure smooth rolling restart of credentials without impacting client behavior.

There are issues from both the fronts when introducing credentials for the first time.
1. Aerospike server is expected to have downtime for the cluster.
2. Client has to be in sync with the downtime. And potentially if I have multiple clients, it is going to be super tricky to have all deployments in sync
