### ISSUE TITLE
Value class does not support char and byte types

### ISSUE THREAD

**Issue by Aloren** [aerospike/aerospike-client-java#75]
There are multiple implementations of `Value` class, e.g.:
`DoubleValue`, `BooleanValue` etc. 
If I want to store primitive of type `byte` or `char` -- `BlobValue` is used for storing.
Why there is no `ByteValue`?

**Comment by BrianNichols** [comment]
This is a server question.  The client doesn't support a byte value, because the server doesn't support a byte value.

BooleanValue is not supported by the server either, but it was added on the client to provide an boolean abstraction.  BooleanValue instances send/receive integers to/from the server.

**Comment by Aloren** [comment]
Byte can be saved as integer or as long as I understood. So why not to add ByteValue as it was done for boolean?

**Comment by BrianNichols** [comment]
We will look into adding ByteValue in the next release.

**Comment by BrianNichols** [comment]
Java client 4.0.0 adds ByteValue.

http://www.aerospike.com/download/client/java/4.0.0/
